name: StarWars
version: '${project.version}'
main: org.randomlima.starwars.StarWars
api-version: '1.20'
commands:
  sw.DC17:
    description: A command that gives the player a DC-17.
    usage: /<command>
    permission: sw.admin
  sw.LightSaber:
    description: A command that gives the player a Light Saber.
    usage: /<command>
    permission: sw.admin